In [1]:
from django.shortcuts import render
from django.contrib.auth.models import User
from ratinghome.models import Rateinfo
import pandas as pd
import seaborn as sns
from math import sqrt
import numpy as np
import matplotlib.pyplot as plt
from scipy import spatial
import django
import os
import string    
import random
from registration.models import Profile, Preferences
from destination.models import Place_rating, Places
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ourproject.settings')
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
django.setup()

ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

In [3]:
import pandas as pd
df = pd.read_csv('../ratings7.csv')

FileNotFoundError: [Errno 2] No such file or directory: '../ratings7.csv'

In [122]:
df

,name,482 Ramaroshan province no. 7,289 Ghorepani Poon Hill Trek province no. 4,120 Vata Mandir province no. 2,"56 Gokyo lake, solukhumbu province no. 1",271 International Mountain Museum province no.4,195 Sundari Chowk province no.3,243 Tilicho Lake province no. 4,275 World Peace Pagoda province no. 4,425 Siwalik Hills province no. 5,...,"463 Mulpani Botanical Garden, salyan province no. 6",481 Saileshwori Temple province no. 7,263 Kaligandaki River province no. 4,467 Kakre Bihar-the other Lumbini province no. 6,176 Thimi province no. 3,35 Sano Pathibhara province no. 1,376 Satyawati lake province no. 5,155 Daman province no. 3,104 Manik Dah province no. 2,168 Ashok Binayak Temple province no.3
0,Ranish Devkota,3.0,3.0,2.0,1.0,2.0,3.0,1.0,1.0,2.0,...,2.0,2.0,2.0,2.0,3.0,2.0,3.0,2.0,2.0,4.0
1,Drishti Dahal,2.0,3.0,5.0,NaN,2.0,2.0,2.0,3.0,5.0,...,3.0,NaN,1.0,3.0,4.0,4.0,NaN,2.0,4.0,4.0
2,Kshitij Basnet,3.0,NaN,5.0,4.0,5.0,4.0,5.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,5.0,3.0,NaN,NaN,5.0
3,rajan,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Prabin Aryal,3.0,3.0,3.0,4.0,2.0,1.0,5.0,4.0,3.0,...,2.0,1.0,4.0,3.0,2.0,2.0,1.0,2.0,1.0,1.0
5,Sneha Chhetri,3.0,4.0,3.0,5.0,4.0,5.0,5.0,4.0,5.0,...,5.0,4.0,4.0,5.0,4.0,5.0,5.0,4.0,5.0,4.0
6,Sinam Adhikari,4.0,3.0,4.0,4.0,NaN,NaN,5.0,5.0,NaN,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Binita Bastola,3.0,3.0,3.0,4.0,2.0,2.0,5.0,4.0,5.0,...,4.0,4.0,4.0,2.0,4.0,2.0,3.0,3.0,3.0,3.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
df = df.fillna(0)

In [124]:
df

,name,482 Ramaroshan province no. 7,289 Ghorepani Poon Hill Trek province no. 4,120 Vata Mandir province no. 2,"56 Gokyo lake, solukhumbu province no. 1",271 International Mountain Museum province no.4,195 Sundari Chowk province no.3,243 Tilicho Lake province no. 4,275 World Peace Pagoda province no. 4,425 Siwalik Hills province no. 5,...,"463 Mulpani Botanical Garden, salyan province no. 6",481 Saileshwori Temple province no. 7,263 Kaligandaki River province no. 4,467 Kakre Bihar-the other Lumbini province no. 6,176 Thimi province no. 3,35 Sano Pathibhara province no. 1,376 Satyawati lake province no. 5,155 Daman province no. 3,104 Manik Dah province no. 2,168 Ashok Binayak Temple province no.3
0,Ranish Devkota,3.0,3.0,2.0,1.0,2.0,3.0,1.0,1.0,2.0,...,2.0,2.0,2.0,2.0,3.0,2.0,3.0,2.0,2.0,4.0
1,Drishti Dahal,2.0,3.0,5.0,0.0,2.0,2.0,2.0,3.0,5.0,...,3.0,0.0,1.0,3.0,4.0,4.0,0.0,2.0,4.0,4.0
2,Kshitij Basnet,3.0,0.0,5.0,4.0,5.0,4.0,5.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,0.0,5.0
3,rajan,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Prabin Aryal,3.0,3.0,3.0,4.0,2.0,1.0,5.0,4.0,3.0,...,2.0,1.0,4.0,3.0,2.0,2.0,1.0,2.0,1.0,1.0
5,Sneha Chhetri,3.0,4.0,3.0,5.0,4.0,5.0,5.0,4.0,5.0,...,5.0,4.0,4.0,5.0,4.0,5.0,5.0,4.0,5.0,4.0
6,Sinam Adhikari,4.0,3.0,4.0,4.0,0.0,0.0,5.0,5.0,0.0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,Binita Bastola,3.0,3.0,3.0,4.0,2.0,2.0,5.0,4.0,5.0,...,4.0,4.0,4.0,2.0,4.0,2.0,3.0,3.0,3.0,3.0
8,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [125]:
for cname,cdata in df.iteritems():
    if cname == 'name':
        continue;
    a = cname.split()
    b = int(a[0])
    df.rename(columns={cname:b}, inplace=True)

In [126]:
df

,name,482,289,120,56,271,195,243,275,425,...,463,481,263,467,176,35,376,155,104,168
0,Ranish Devkota,3.0,3.0,2.0,1.0,2.0,3.0,1.0,1.0,2.0,...,2.0,2.0,2.0,2.0,3.0,2.0,3.0,2.0,2.0,4.0
1,Drishti Dahal,2.0,3.0,5.0,0.0,2.0,2.0,2.0,3.0,5.0,...,3.0,0.0,1.0,3.0,4.0,4.0,0.0,2.0,4.0,4.0
2,Kshitij Basnet,3.0,0.0,5.0,4.0,5.0,4.0,5.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,0.0,5.0
3,rajan,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Prabin Aryal,3.0,3.0,3.0,4.0,2.0,1.0,5.0,4.0,3.0,...,2.0,1.0,4.0,3.0,2.0,2.0,1.0,2.0,1.0,1.0
5,Sneha Chhetri,3.0,4.0,3.0,5.0,4.0,5.0,5.0,4.0,5.0,...,5.0,4.0,4.0,5.0,4.0,5.0,5.0,4.0,5.0,4.0
6,Sinam Adhikari,4.0,3.0,4.0,4.0,0.0,0.0,5.0,5.0,0.0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,Binita Bastola,3.0,3.0,3.0,4.0,2.0,2.0,5.0,4.0,5.0,...,4.0,4.0,4.0,2.0,4.0,2.0,3.0,3.0,3.0,3.0
8,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [127]:
df['name'] = df['name'].str.strip().str.replace(' ','')

In [128]:
df =df.dropna()
df

,name,482,289,120,56,271,195,243,275,425,...,463,481,263,467,176,35,376,155,104,168
0,RanishDevkota,3.0,3.0,2.0,1.0,2.0,3.0,1.0,1.0,2.0,...,2.0,2.0,2.0,2.0,3.0,2.0,3.0,2.0,2.0,4.0
1,DrishtiDahal,2.0,3.0,5.0,0.0,2.0,2.0,2.0,3.0,5.0,...,3.0,0.0,1.0,3.0,4.0,4.0,0.0,2.0,4.0,4.0
2,KshitijBasnet,3.0,0.0,5.0,4.0,5.0,4.0,5.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,0.0,5.0
3,rajan,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,PrabinAryal,3.0,3.0,3.0,4.0,2.0,1.0,5.0,4.0,3.0,...,2.0,1.0,4.0,3.0,2.0,2.0,1.0,2.0,1.0,1.0
5,SnehaChhetri,3.0,4.0,3.0,5.0,4.0,5.0,5.0,4.0,5.0,...,5.0,4.0,4.0,5.0,4.0,5.0,5.0,4.0,5.0,4.0
6,SinamAdhikari,4.0,3.0,4.0,4.0,0.0,0.0,5.0,5.0,0.0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,BinitaBastola,3.0,3.0,3.0,4.0,2.0,2.0,5.0,4.0,5.0,...,4.0,4.0,4.0,2.0,4.0,2.0,3.0,3.0,3.0,3.0

In [129]:
for i in range(0, len(df.index)):
    df.at[i,'name']='test'+df.at[i,'name']+str(random.randint(0,100))

In [130]:
df

,name,482,289,120,56,271,195,243,275,425,...,463,481,263,467,176,35,376,155,104,168
0,testRanishDevkota63,3.0,3.0,2.0,1.0,2.0,3.0,1.0,1.0,2.0,...,2.0,2.0,2.0,2.0,3.0,2.0,3.0,2.0,2.0,4.0
1,testDrishtiDahal63,2.0,3.0,5.0,0.0,2.0,2.0,2.0,3.0,5.0,...,3.0,0.0,1.0,3.0,4.0,4.0,0.0,2.0,4.0,4.0
2,testKshitijBasnet73,3.0,0.0,5.0,4.0,5.0,4.0,5.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,0.0,5.0
3,testrajan72,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,testPrabinAryal1,3.0,3.0,3.0,4.0,2.0,1.0,5.0,4.0,3.0,...,2.0,1.0,4.0,3.0,2.0,2.0,1.0,2.0,1.0,1.0
5,testSnehaChhetri55,3.0,4.0,3.0,5.0,4.0,5.0,5.0,4.0,5.0,...,5.0,4.0,4.0,5.0,4.0,5.0,5.0,4.0,5.0,4.0
6,testSinamAdhikari88,4.0,3.0,4.0,4.0,0.0,0.0,5.0,5.0,0.0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,testBinitaBastola13,3.0,3.0,3.0,4.0,2.0,2.0,5.0,4.0,5.0,...,4.0,4.0,4.0,2.0,4.0,2.0,3.0,3.0,3.0,3.0

In [131]:
df.set_index('name',inplace=True)

In [132]:
df

,482,289,120,56,271,195,243,275,425,50,...,463,481,263,467,176,35,376,155,104,168
name,,,,,,,,,,,,,,,,,,,,,
testRanishDevkota63,3.0,3.0,2.0,1.0,2.0,3.0,1.0,1.0,2.0,3.0,...,2.0,2.0,2.0,2.0,3.0,2.0,3.0,2.0,2.0,4.0
testDrishtiDahal63,2.0,3.0,5.0,0.0,2.0,2.0,2.0,3.0,5.0,3.0,...,3.0,0.0,1.0,3.0,4.0,4.0,0.0,2.0,4.0,4.0
testKshitijBasnet73,3.0,0.0,5.0,4.0,5.0,4.0,5.0,5.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,0.0,5.0
testrajan72,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
testPrabinAryal1,3.0,3.0,3.0,4.0,2.0,1.0,5.0,4.0,3.0,3.0,...,2.0,1.0,4.0,3.0,2.0,2.0,1.0,2.0,1.0,1.0
testSnehaChhetri55,3.0,4.0,3.0,5.0,4.0,5.0,5.0,4.0,5.0,5.0,...,5.0,4.0,4.0,5.0,4.0,5.0,5.0,4.0,5.0,4.0
testSinamAdhikari88,4.0,3.0,4.0,4.0,0.0,0.0,5.0,5.0,0.0,0.0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
testBinitaBastola13,3.0,3.0,3.0,4.0,2.0,2.0,5.0,4.0,5.0,5.0,...,4.0,4.0,4.0,2.0,4.0,2.0,3.0,3.0,3.0,3.0

In [133]:
for index,row in df.iterrows():  
    ran = ''.join(random.choices(string.ascii_uppercase + string.digits, k = 15))  
    password = str(ran)
    User.objects.create_user(username=index,password=password)

In [ ]:
for index,row in df.iterrows(): 
    for col in df:
        queryplace = Places.objects.get(rateinfo__pID=col)
        queryuser = User.objects.get(username=index)
        data=Place_rating()
        data.user=queryuser
        data.place=queryplace
        if row[col]>0:
            data.rate = row[col]
            data.save()